name: Basic CI

on:
  push:
    branches: ["main", "develop", "cicd"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    environment: Production
    env:
      NEXT_PUBLIC_GROUP_TOKEN: ${{ secrets.FRONT_GROUP_TOKEN }}
      BETTER_AUTH_SECRET: ${{ secrets.FRONT_BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.FRONT_BETTER_AUTH_URL }}
      DATABASE_URL: ${{ secrets.FRONT_DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Verify frontend environment variables
        run: |
          if [ -z "$DATABASE_URL" ]; then echo "DATABASE_URL not set" && exit 1; else echo "✅ DATABASE_URL set"; fi
          if [ -z "$BETTER_AUTH_SECRET" ]; then echo "BETTER_AUTH_SECRET not set" && exit 1; else echo "✅ BETTER_AUTH_SECRET set"; fi
          if [ -z "$BETTER_AUTH_URL" ]; then echo "BETTER_AUTH_URL not set" && exit 1; else echo "✅ BETTER_AUTH_URL set"; fi
          if [ -z "$NEXT_PUBLIC_GROUP_TOKEN" ]; then echo "NEXT_PUBLIC_GROUP_TOKEN not set" && exit 1; else echo "✅ NEXT_PUBLIC_GROUP_TOKEN set"; fi
        working-directory: front

      - name: Install backend dependencies
        run: npm ci
        working-directory: back

      - name: Start backend in background
        run: npm start &
        working-directory: back

      - name: Wait for backend
        run: npx wait-on http://localhost:8000
        working-directory: front

      - name: Install frontend dependencies
        run: npm ci
        working-directory: front

      - name: Build frontend
        run: npm run build
        working-directory: front

      - name: Run frontend tests
        run: npm test || echo "No tests found"
        working-directory: front

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    environment: Production
    env:
      JWT_ACCESS_SECRET: ${{ secrets.BACK_JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.BACK_JWT_REFRESH_SECRET }}
      DATABASE_URL: ${{ secrets.BACK_DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Verify backend environment variables
        run: |
          if [ -z "$DATABASE_URL" ]; then echo "DATABASE_URL not set" && exit 1; else echo "✅ DATABASE_URL set"; fi
          if [ -z "$JWT_ACCESS_SECRET" ]; then echo "JWT_ACCESS_SECRET not set" && exit 1; else echo "✅ JWT_ACCESS_SECRET set"; fi
          if [ -z "$JWT_REFRESH_SECRET" ]; then echo "JWT_REFRESH_SECRET not set" && exit 1; else echo "✅ JWT_REFRESH_SECRET set"; fi
        working-directory: back

      - name: Install backend dependencies
        run: npm ci
        working-directory: back

      - name: Run backend tests
        run: npm test || echo "No tests found"
        working-directory: back
